application: eflowv1
version: development
runtime: php55
api_version: 1

handlers:

- url: /(.+\.php)$
  script: \1 
 
- url: /Mail(.+\.php)$
  script: \1
  
- url: /eflow/Manuals
  static_dir: eflow/Manuals  
  
- url: /eflow/images
  static_dir: eflow/images
    
- url: /eflow/scripts/controllers
  static_dir: eflow/scripts/controllers
   
- url: /eflow/scripts/externals
  static_dir: eflow/scripts/externals
  
- url: /eflow/styles
  static_dir: eflow/styles
  
- url: /eflow/views
  static_dir: eflow/views
 
- url: /eflow
  static_dir: eflow
  
- url: /
  script: Send_Mail.php
  login: admin